# Meta

title:         "Bulma中文文档: a modern CSS framework based on Flexbox"
description:   "Bulma中文文档Bulma is an open source CSS framework based on Flexbox and built with Sass. It's 100% responsive, fully modular, and available for free."
env:           "production"

# Build

markdown:      kramdown
permalink:     pretty
url:            https://img.higrid.net
exclude:       ['icons', 'node_modules', 'templates', '.babelrc', 'bulma-docs.sass', 'docker-compose.yml', 'package.json', 'yarn.lock']

# Variables

documentation: "https://img.higrid.net/documentation/overview/start/"
download:      https://github.com/jgthms/bulma/releases/download/0.9.4/bulma-0.9.4.zip
github:        https://github.com/jgthms/bulma
twitter:       https://twitter.com/jgthms
version:       0.9.4
